include:
  # - path: tsdproxy/docker-compose.yml
    # env_file: tsdproxy/laptop.env
  # - path: karakeep/docker-compose.yml
  #   env_file: karakeep/.env
  # - ollama/docker-compose.yml
  - path: soft-serve/docker-compose.yml
    env_file:
      - laptop.env
      - soft-serve/.env