
services:
  # https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Helsinki'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - "${DATA_DIR}/pihole/etc-pihole:/etc/pihole"
      - "${DATA_DIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      # needed because docker keeps pointing resolv to 127.0.0.11 for some reason
#      - "./pihole_resolv.conf:/etc/resolv.conf"
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped # Recommended but not required (DHCP needs NET_ADMIN)

  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/tsdproxy/data:/data
    environment:
      - TSDPROXY_AUTHKEY=${TSDPROXY_AUTHKEY}
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
  nginx:
    image: nginx
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "nginx"
    ports:
      - "8080:80"