include:
  - path: tsdproxy/docker-compose.yml
    env_file: 
      - tsdproxy/nuc.env
      - nuc.env
  - path: karakeep/docker-compose.yml
    env_file: 
      - karakeep/.env
      - nuc.env
  - path: backrest/docker-compose.yml
    env_file: 
      - nuc.env
      - backrest/nuc.env
  - path: soft-serve/docker-compose.yml
    env_file:
      - nuc.env
      - soft-serve/.env
