networks:
  backrest-network:
      driver: bridge
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    user: "${UID_GID:-1000:1000}"
    volumes:
      # this is fine since anything in the backrest dir is excluded from
      # being backed up.
      - ${DATA_DIR}/backrest/data:/data
      # tracked in git
      - "./config-${DOCKER_HOST_NAME}:/config"
      - ${DATA_DIR}/backrest/cache:/cache
      - ${DATA_DIR}/backrest/tmp:/tmp
      # data to back up
      - ${DATA_DIR}:/containerdata
      # destination data
      - /mnt/backrest:/destination
      - ./manage_containers.sh:/manage_containers.sh
    env_file:
      - ../shared.env
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - BACKUP_LIST=${BACKUP_LIST}
      - DOCKER_HOST=tcp://backrest-socketproxy:2375
    networks:
      - backrest-network
    ports:
      # todo: this can be disabled once everything is configured 
      - "9898:9898"
    restart: unless-stopped
    depends_on:
      - backrest-socketproxy
  
  backrest-socketproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: backrest-socketproxy
    env_file:
      - ../shared.env
    environment:
      - CONTAINERS=1
      - POST=1
      - ALLOW_START=1
      - ALLOW_STOP=1
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - backrest-network
    # uncomment this to get access to the docker socket on localhost
    # ports:
    #   - "127.0.0.1:2375:2375"